import { StyleSheet, Platform, StatusBar } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  scrollView: {
    flex: 1,
    width: '100%',
    backgroundColor: 'transparent',
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
    paddingTop: Platform.OS === 'android' ? 10 : 20,
    backgroundColor: 'transparent',
  },
  centered: {
    width: '90%',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  title: {
    color: '#fff',
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 32,
    textAlign: 'center',
  },
  label: {
    color: '#fff',
    fontSize: 18,
    marginBottom: 12,
    textAlign: 'center',
  },
  subtitle: {
    color: '#888',
    fontSize: 16,
    marginTop: 16,
    textAlign: 'center',
  },
  input: {
    width: 250,
    padding: 14,
    borderRadius: 8,
    backgroundColor: '#23242a',
    color: '#fff',
    fontSize: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#333',
  },
  button: {
    width: 250,
    backgroundColor: '#3A3F47',
    paddingVertical: 10,
    borderRadius: 8,
    marginTop: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonActive: {
    backgroundColor: '#4CAF50',
  },
  secondaryButton: {
    backgroundColor: '#666',
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
    letterSpacing: 1,
  },
  readyButton: {
    backgroundColor: '#4CAF50',
  },
  notReadyButton: {
    backgroundColor: '#FF9800',
  },
  error: {
    color: '#ff6b6b',
    marginBottom: 8,
    fontSize: 14,
  },
  gameCodeContainer: {
    backgroundColor: '#23242a',
    padding: 20,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#4CAF50',
    marginVertical: 20,
  },
  gameCode: {
    color: '#4CAF50',
    fontSize: 24,
    fontWeight: 'bold',
    letterSpacing: 2,
    textAlign: 'center',
  },
  gameCodeLabel: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 8,
  },
  copyHint: {
    color: '#888',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 8,
    fontStyle: 'italic',
  },
  debugText: {
    color: '#fff',
    fontSize: 16,
    marginTop: 20,
  },
  clearButton: {
    backgroundColor: '#6b2d35',
  },
  gameInfo: {
    width: '90%',
    alignSelf: 'center',
    marginVertical: 20,
    backgroundColor: 'transparent',
  },
  playerRow: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    backgroundColor: '#23242a',
    padding: 12,
    borderRadius: 8,
    marginVertical: 4,
    width: '100%',
  },
  playerText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  playerStatus: {
    color: '#888',
    fontSize: 14,
  },
  readyStatus: {
    color: '#ff6b6b',
    fontSize: 14,
    fontWeight: '600',
  },
  ready: {
    color: '#4CAF50',
  },
  simulatedTag: {
    color: '#FFA500',
    fontSize: 12,
    fontWeight: 'bold',
  },
  simInfo: {
    width: '90%',
    marginVertical: 20,
    alignItems: 'center',
  },
  simControls: {
    width: '90%',
    marginVertical: 20,
  },
  simPlayerRow: {
    backgroundColor: '#23242a',
    padding: 12,
    borderRadius: 8,
    marginVertical: 4,
  },
  currentCharacterContainer: {
    width: '90%',
    marginBottom: 20,
  },
  characterName: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 2,
  },
  characterDescription: {
    color: '#666',
    fontSize: 14,
    fontStyle: 'italic',
  },
  characterNameWhite: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.8)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  characterCard: {
    backgroundColor: '#2a2d35',
    padding: 16,
    borderRadius: 8,
    marginVertical: 4,
    width: '100%',
    borderWidth: 1,
    borderColor: '#3a3d45',
  },
  characterInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  playButton: {
    backgroundColor: '#4CAF50',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  playButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  scriptContainer: {
    backgroundColor: '#23242a',
    padding: 16,
    borderRadius: 8,
    marginVertical: 4,
  },
  scriptText: {
    color: '#fff',
    fontSize: 16,
  },
  primaryButton: {
    backgroundColor: '#4CAF50',
  },
  testSection: {
    width: '90%',
    marginVertical: 20,
  },
  testTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  testButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    width: '100%',
  },
  testButton: {
    width: '48%',
    backgroundColor: '#FF9800',
    marginVertical: 4,
  },
  testButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  gameTestButton: {
    backgroundColor: '#FF9800',
    marginVertical: 8,
  },
  selectedCard: {
    backgroundColor: '#4CAF50',
    borderColor: '#4CAF50',
    borderWidth: 3,
    borderRadius: 12,
  },
  selectedText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 8,
  },
  centeredText: {
    textAlign: 'center',
  },
  collapsibleHeader: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'transparent',
    paddingVertical: 12,
    paddingHorizontal: 0,
    borderRadius: 8,
  },
  collapsibleHeaderText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginRight: 8,
  },
  collapsibleArrow: {
    color: '#888',
    fontSize: 24,
  },
  playerStatusContainer: {
    marginTop: 12,
  },
  showPlayerStatus: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  centeredButtonContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    display: 'flex',
    flexDirection: 'row',
    paddingBottom: 20,
  },

  gameCard: {
    backgroundColor: '#23242a',
    padding: 16,
    borderRadius: 8,
    marginVertical: 4,
    width: '100%',
  },
  gameCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  gameTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  checkmark: {
    color: '#4CAF50',
    fontSize: 18,
    fontWeight: 'bold',
  },
  gameDescription: {
    color: '#888',
    fontSize: 16,
    marginBottom: 8,
  },
  comingSoonBadge: {
    backgroundColor: '#FF9800',
    padding: 4,
    borderRadius: 4,
    marginTop: 8,
  },
  comingSoonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  comingSoonCard: {
    backgroundColor: '#333',
    opacity: 0.7,
  },
  selectedGameCard: {
    borderWidth: 2,
    borderColor: '#4CAF50',
  },
  launchButton: {
    backgroundColor: '#4CAF50',
    marginTop: 8,
    alignItems: 'center',
    alignSelf: 'center',
  },
  detailsButtonSmall: {
    backgroundColor: 'transparent',
    padding: 8,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    width: 35,
    height: 35,
  },
  detailsButtonTextSmall: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'normal',
    lineHeight: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 12,
    width: '90%',
    height: '80%',
    zIndex: 1001,
    position: 'relative',
  },
  modalScroll: {
    flex: 1,
  },
  modalCloseX: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: 'rgba(255, 152, 0, 0.9)',
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1002,
  },
  modalCloseXText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  modalTitle: {
    color: '#000',
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  modalDescription: {
    color: '#333',
    fontSize: 16,
    marginBottom: 16,
  },
  modalInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  modalInfoLabel: {
    color: '#000',
    fontSize: 16,
    fontWeight: '600',
  },
  modalInfoText: {
    color: '#333',
    fontSize: 16,
  },
  modalSectionTitle: {
    color: '#000',
    fontSize: 18,
    fontWeight: 'bold',
    marginTop: 16,
    marginBottom: 8,
  },
  characterItem: {
    marginBottom: 8,
    paddingVertical: 4,
  },
  characterName: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 2,
  },
  characterDescription: {
    color: '#666',
    fontSize: 14,
    fontStyle: 'italic',
  },

  modalCloseButton: {
    backgroundColor: '#FF9800',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  modalCloseButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  hamburgerIcon: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  menuOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    zIndex: 2000,
  },
  menuContent: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 100 : 70,
    right: 20,
    backgroundColor: '#23242a',
    borderRadius: 12,
    padding: 16,
    minWidth: 200,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#3a3d45',
  },
  menuItemText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 12,
  },
  menuItemLast: {
    borderBottomWidth: 0,
  },
  helpModalContent: {
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 12,
    width: '95%',
    height: '90%',
    zIndex: 1001,
    position: 'relative',
  },
  helpSection: {
    marginBottom: 20,
  },
  helpSectionTitle: {
    color: '#000',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 12,
  },
  helpSectionContent: {
    color: '#333',
    fontSize: 16,
    lineHeight: 24,
    marginBottom: 8,
  },
  textSizeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  textSizeOptionSelected: {
    backgroundColor: '#e3f2fd',
  },
  textSizeOptionText: {
    color: '#000',
    fontSize: 16,
    flex: 1,
  },
  textSizeOptionCheck: {
    color: '#4CAF50',
    fontSize: 18,
    fontWeight: 'bold',
  },
  faqItem: {
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  faqQuestion: {
    color: '#000',
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  faqAnswer: {
    color: '#333',
    fontSize: 14,
    lineHeight: 20,
  },
  // Enhanced Player Controls Styles
  playerInfo: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  playerControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
    width: '100%',
  },
  readyStatusButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: '#ff6b6b',
    marginTop: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  readyStatusButtonActive: {
    backgroundColor: '#4CAF50',
  },
  smallButton: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 70,
    flex: 1,
  },
  viewScriptButton: {
    backgroundColor: '#2196F3',
  },
  markReadyButton: {
    backgroundColor: '#4CAF50',
  },
  markNotReadyButton: {
    backgroundColor: '#FF9800',
  },
  removePlayerButton: {
    backgroundColor: '#F44336',
  },
  // My Games Styles
  filterContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    marginBottom: 20,
    gap: 8,
  },
  filterButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  filterButtonActive: {
    backgroundColor: '#FF9800',
    borderColor: '#FF9800',
  },
  gamesList: {
    width: '100%',
    marginBottom: 20,
  },
  gameCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  gameCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  gameCardDetails: {
    marginBottom: 16,
  },
  gameDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  gameCardActions: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'flex-start',
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  statusBadgeLobby: {
    backgroundColor: '#4CAF50',
  },
  statusBadgeInProgress: {
    backgroundColor: '#FF9800',
  },
  statusBadgeCompleted: {
    backgroundColor: '#2196F3',
  },
  actionButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    minWidth: 60,
    alignItems: 'center',
  },
  actionButtonPrimary: {
    backgroundColor: '#4CAF50',
  },
  actionButtonSecondary: {
    backgroundColor: '#2196F3',
  },
  actionButtonDanger: {
    backgroundColor: '#F44336',
  },
  header: {
    color: '#fff',
    fontSize: 32,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 24,
    marginBottom: 32,
  },
  headerWithPadding: {
    color: '#fff',
    fontSize: 32,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 40,
    marginBottom: 32,
  },
  viewContainer: {
    width: '90%',
    alignSelf: 'center',
    backgroundColor: 'transparent',
  },
  
  // New styles for UnifiedLobbyView
  inviteSettingsContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    padding: 16,
    marginTop: 8,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    justifyContent: 'space-between',
  },
  textInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 4,
    padding: 8,
    color: '#fff',
    fontSize: 16,
    flex: 1,
    marginLeft: 12,
  },
  pickerRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginLeft: 12,
    flex: 1,
  },
  pickerOption: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginRight: 8,
    marginBottom: 8,
  },
  pickerOptionSelected: {
    backgroundColor: '#4CAF50',
  },
  pickerOptionText: {
    color: '#fff',
    fontSize: 14,
  },
  pickerOptionTextSelected: {
    color: '#fff',
    fontWeight: 'bold',
  },
  characterActions: {
    flexDirection: 'column',
    gap: 8,
  },
  characterButtonRow: {
    flexDirection: 'row',
    width: '100%',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#2C2C2C',
    borderRadius: 12,
    padding: 24,
    width: '90%',
    maxWidth: 400,
  },
  modalTitle: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 16,
    textAlign: 'center',
  },
  modalDescription: {
    color: '#ccc',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
  },
});

export default styles; 